# Site settings
title: Joe Martin Design
author: Joe Martin
email: josephmartin09@gmail.com
url: www.joemartindesign.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: Web and Mobile Developer - Systems Programmer - Software Engineer

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: 18bc9c
  # secondary: 2c3e50 
  # secondary-dark: 233140 

  # Second Try
  primary: a0d6b4
  primary-dark: 18bc9c  # Nothing yet
  secondary: 2c3e50
  secondary-dark: 233140
  background: f5f3e9   #f5f3e9  #f0eee1  #abcdef

# About settings
about:
  left: "Hi, my name is Joseph Martin. I am a graduate of the University of Maryland with degrees in Mechanical Engineering and Computer Science. In the past, I worked as an Engineering Intern at Silver Palm LLC, developing communications code for micro-controllers in a variety of signal intelligence applications."
  right: "I now work as an independent software contractor and have experience with web and mobile apps, embedded systems programming, network programming, and algorithm development. I consider myself a student of life, and am always looking for a challenge and a new way to learn."
# Footer settings
footer:
  copyright: Joseph Martin
  location: Located in the Washington DC Area
  social: Find me on the Web
  credits: Dedicated Developer

# Credits content
credits: 'I develop as a contractor because I want to stay passionate about the work that I do.  Come back soon to see my latest work!'


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: linkedin
    url: https://www.linkedin.com/pub/joseph-martin/b2/861/265
  - title: github
    url: http://github.com/josephmartin09

# Postal address (add as many lines as necessary)
address:
#   - line: 3481 Melrose Place
  - line: Silver Spring, MD 20901

# Build settings
# markdown: kramdown
# permalink: pretty